name: Generate Release Notes

on:
  release:
    types: [published]

jobs:
  notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate Notes
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
