name: Deployment Pipeline (Simulated)

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run lint
      - name: Run ESLint
        run: npm run lint

      # Step 5: Run tests
      - name: Run Jest tests
        run: npm test

      # Step 6: Simulate deployment
      - name: Build project
        run: echo "Building project for deployment..."

      - name: Simulate Deployment
        run: echo "✅ Deployment simulated successfully!"
